/* ========================================
 *
 * This file is automatically generated by CyDesigner
 * and should not be edited by hand.
 *
 * ========================================
*/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Volume_ADC.h>
#include <Button_aliases.h>
#include <Button.h>
#include <Volum_Line_aliases.h>
#include <TX_aliases.h>
#include <TX.h>
#include <UART.h>
#include <LED_Control_Reg.h>
#include <dPins_LSB_aliases.h>
#include <dPins_LSB.h>
#include <dPins_MSB_aliases.h>
#include <dPins_MSB.h>
#include <timer_clock.h>
#include <Counter_1.h>
#include <Volume_ADC_theACLK.h>
#include <UART_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
